"""empty message

Revision ID: 26e70d2ff149
Revises: 90bd06fb6651
Create Date: 2025-02-19 12:08:28.346604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e70d2ff149'
down_revision = '90bd06fb6651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgUrl', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('imgUrl')

    # ### end Alembic commands ###
